version: '3'
services:
  web:
    container_name: wit-ui
    build: wit-ui
    image: demoaccount/wit-retail-demo_web
    ports:
      - "80:80"
  db:
    container_name: wit-catalog-db
    image: demoaccount/wit-retail-demo_db
    ports:
      - "3300:3306"
  app:
    container_name: wit-catalog-app
    image: demoaccount/wit-retail-demo_app
    ports:
      - "8091:8080"
